# Generated by Django 3.2.9 on 2021-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_formulario_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='feedback',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
