# Generated by Django 3.2.9 on 2021-11-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('alunoid', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=60)),
                ('ra', models.CharField(max_length=20)),
                ('cpf', models.CharField(max_length=14)),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_empresa', to='turma.turma')),
            ],
        ),
    ]
